security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: .css$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: .js$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: .jpeg$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: .jpg$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: .png$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Grupo, role: ROLE_ADMIN }
        #- { path: /, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
