services:
  puertoudes.util:
    class:      "PuertoUDES\CommonBundle\Controller\IndexController"
    arguments:  [@doctrine.orm.entity_manager, @form.factory, @router]
    calls:
          - [setRequest, ['@?request=']]
          - [setResponse, ['@?response=']]
    tags: 
          - { name: knp_paginator.injectable, paginator: knp_paginator }
          
  puestoudes.listener.login:
      class: "PuertoUDES\FosUsuarioBundle\EventListener\SecurityListener"
      arguments: [@security.context, @session,@doctrine.orm.entity_manager]
      tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }