parameters:
#    puerto_udes_fos_usuario.example.class: PuertoUDES\FosUsuarioBundle\Example

services:
#    puerto_udes_fos_usuario.example:
#        class: %puerto_udes_fos_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
